---
- name: Trabalhando com templates
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml    
  tasks:
    - name: Criando o template
      ansible.builtin.template:
        src: template.j2
        dest: /home/leo/desenvolvimento/ansible/exemplo.txt