---
- name: Criação de um usuario
  hosts: all
  remote_user: root
  vars_files:
    - vars.yaml
  tasks:
    - name: Instalar o pacote whois
      ansible.builtin.apt:
        name: whois
        state: present
        update_cache: true

    - name: Gerar senha criptografada
      ansible.builtin.shell: "mkpasswd --method=SHA-512 --rounds=4096 {{ senha }}"
      register: senha_criptografada

    - name: Criar o usuario
      ansible.builtin.user:
        name: "{{ nome }}"
        password: "{{ senha_criptografada.stdout }}"
        state: present
        shell: /bin/bash
        groups: sudo
        append: yes
    - name: Criar o diretorio ssh 
      ansible.builtin.file:
        path: "/home/{{ nome }}/.ssh"
        state: directory
        owner: "{{ nome }}"
        group: "{{ nome }}"
        recurse: true
    - name: Copiar a chave publica
      ansible.builtin.copy:
        src: "/home/leo/.ssh/aula_ansible.pub"
        dest: "/home/{{ nome }}/.ssh/authorized_keys"